#!/usr/bin/env bash

rm -rf dist bin
mkdir -p dist
mkdir -p bin

echo "build src/index.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cp --no-header src/index.ls > dist/index.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js

echo "build src/cli.ls -> bin/cli.js ..."
echo "#!/usr/bin/env node" > bin/cli.js
./node_modules/.bin/lsc -cp --no-header src/cli.ls >> bin/cli.js
chmod 755 bin/cli.js

echo "bundle dist/index.js -> dist/index.bundle.js"
./node_modules/.bin/browserify -s suuid dist/index.js > dist/index.bundle.js
echo "minifying dist/index.bundle.js ..."
cat dist/index.bundle.js | ./node_modules/.bin/buble | ./node_modules/.bin/uglifyjs -m -c > dist/index.bundle.min.js

mkdir -p web/static/assets/lib/suuid
cp dist/* web/static/assets/lib/suuid
echo "done."
